### ISSUE TITLE
enhancement: Use tags to mark releases. 

### ISSUE THREAD

**Issue by krt16s** [TomasValenta/WebCamViewer#2]
It would be great if you could use git tags to mark new releases, e.g. use `git tag $VERSION` and `git push --tags` on commits that change the version/are considered a release. This would ease up auto-updates of your app in the f-droid.org app repo. Especially because you update versioncodes more often then the actual versionnames. This makes sense for developers, but users often look just at the versionname and see the same version got released multiple times (or an update comming to a version they already have installed), so they get confused :)

**Comment by TomasValenta** [comment]
Hi Boris,
thank you for your proposal. This is not the same?
https://github.com/TomasValenta/WebCamViewer/tags
https://github.com/TomasValenta/WebCamViewer/releases
I use Android Studio to manage vcs, not git command line interface. And it seems at the moment, there is no way to add git tags.:
https://youtrack.jetbrains.com/issue/IDEA-77483

**Comment by krt16s** [comment]
Oh, yes, this is the same. Sorry, didn't spot this.

**Comment by TomasValenta** [comment]
No problem ;)

**Comment by TomasValenta** [comment]
Hi Boris,
can you please update the repository on F-Droid to actual version?

**Comment by krt16s** [comment]
I fixed our tag selector, It should auto-update to release builds tonight. Let's see if it works, otherwise I will manually do the upgrade tomorrow.

**Comment by TomasValenta** [comment]
Ok,
thank you Boris ;)

**Comment by TomasValenta** [comment]
Hello @krt16s,
it seems that the situation is still the same ;-)

**Comment by krt16s** [comment]
It did get updated in the metadata...

````
2015-03-06 05:14 F-Droid Builder    o Update Kontalk to 3.0-beta8.1 (42)
````

... but a long with other builds, it's still missing. Seems to be an issue with the buildserver. Nothing I can fix :/ I will try to ping @CiaranG , but I am away for another week, so I might not catch him on IRC.
